name: Test Runner
on: [push]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: astemes
      - name: Checkout Tools
        uses: actions/checkout@v4
        with:
          repository: astemes/astemes-github-actions
          ref: main
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/astemes-github-actions
  test:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/astemes-github-actions/runLUnit
        with:
          project-path: "source\\project.lvproj"
  build-exe:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/astemes-github-actions/buildLVBuildSpec
        with:
          token: ${{ steps.app-token.outputs.token }}
          project-path: "source\\project.lvproj"
          build-spec: "Application"
  build-pkg:
    runs-on: self-hosted
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: astemes
      - uses: ./.github/actions/astemes-github-actions/buildLVBuildSpec
        with:
          token: ${{ steps.app-token.outputs.token }}
          project-path: "source\\project.lvproj"
          build-spec: "Package"