name: Test Runner
on: [push]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: astemes
      - name: Checkout Tools
        uses: actions/checkout@v4
        with:
          repository: astemes/astemes-github-actions
          ref: main
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/astemes-github-actions
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        shell: powershell
        run: |
          $version = $env:GITHUB_REF -replace '^refs/tags/v',''
          Write-Host "Version is $version"
          Write-Output "version=$version >> $GITHUB_OUTPUT"
      - name: Print version
        run: echo "Using version ${{ steps.get_version.outputs.version }}"
  docs:
    needs: checkout
    runs-on: self-hosted
    steps:
      - name: Build MKDocs
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/astemes-github-actions/buildDocs
        with:
            project-title: "Docs Sandbox"
            author: "Anton Sundqvist"
            initial-release: "2025"

  # test:
  #   needs: checkout
  #   runs-on: self-hosted
  #   steps:
  #     - uses: ./.github/actions/astemes-github-actions/runLUnit
  #       with:
  #         project-path: "source\\project.lvproj"
  # build-exe:
  #   needs: test
  #   runs-on: self-hosted
  #   steps:
  #     - uses: ./.github/actions/astemes-github-actions/buildLVBuildSpec
  #       with:
  #         project-path: "source\\project.lvproj"
  #         build-spec: "Application"
  # build-pkg:
  #   needs: build-exe
  #   runs-on: self-hosted
  #   steps:
  #     - uses: ./.github/actions/astemes-github-actions/buildLVBuildSpec
  #       with:
  #         project-path: "source\\project.lvproj"
  #         build-spec: "Package"