name: Test Runner
on: [push]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
  test:
    runs-on: self-hosted
    steps:
      - uses: Astemes/astemes-github-actions/runLUnit@main
        with:
          project-path: "source\\project.lvproj"

  build:
    runs-on: self-hosted
    steps:
      - uses: Astemes/astemes-github-actions/buildLVBuildSpec@main
        with:
          project-path: "source\\project.lvproj"
          build-spec: "Application"
      - uses: Astemes/astemes-github-actions/buildLVBuildSpec@main
        with:
          project-path: "source\\project.lvproj"
          build-spec: "Package"